# coding: utf-8 
quotes = ['\"There’s nothing noble in being superior to your fellow men. True nobility lies in being superior to your former self.” - Ernest Hemingway',
          '\"The mind is its own place and in itself, can make a Heaven of Hell, a Hell of Heaven." - John Milton, Paradise Lost',
          '\"Life is what happens to you while you\'re busy making other plans." - John Lennon',
          '\"In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move." \n- Douglas Adams, Hitchhiker\'s Guide to the Galaxy',
          '“I cannot remember the books I\'ve read any more than the meals I have eaten; even so, they have made me.” - Ralph Waldo Emerson',
          '“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.” ― Ralph Waldo Emerson',
          '“The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.” ― Ralph Waldo Emerson',
          '"If you tell the truth, you don\'t have to remember anything." - Mark Twain',
          '"Whatever you are, be a good one." - Abraham Lincoln',
          '“We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.” -Carl Sagan',
          '"I did not get my Spaghetti-Os, I got spaghetti. I want the press to know this." - Thomas J. Grasso, last words before being executed',
          '"When life gives you lemons, just say \'Fuck the lemons!\' and bail." - I Love You, Man',
          '"Everyone in the world is a genius, but if you judge a fish by its ability to climb a tree it will spend its entire life believing that it is stupid."',
          '"If you trust in yourself...and believe in your dreams...and follow your star...you\'ll still get beaten by people who spent their time working hard and learning things and weren\'t so lazy." - Terry Pratchett, The Wee Free Men',
          '"Remember, if another man can do it then so can you"',
          '"If you want something you\'ve never had. You gotta do something you\'ve never done"',
          '“Sucking at something is the first step to being sorta good at something.” - Jake the Dog, Adventure Time',
          '“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.” - Earl Nightingale',
          '"He who knows he has enough is rich" -Tao Te Ching',
          '"Meet me in the middle," says the unjust man. You take a step towards him, he takes a step back. "Meet me in the middle," says the unjust man.',
          '“Never put off till tomorrow what may be done day after tomorrow just as well.”  ― Mark Twain',
          '"We judge others by their actions,but we judge ourselves by our intentions"',
          '“The snowflake doesn\'t know that it is part of the avalanche.”',
          '“Even the longest days are twenty-four hours.”',
          '“Worrying means you suffer twice” - Newt Scamander',
          '"The grass is greenest where you water it."',
          '"Be kind, for everyone you meet is fighting a hard battle."',
          '"Isn\'t it funny how day-by-day nothing changes, but when you look back everything is different." - C.S. Lewis',
          '“In three words, I can sum up everything I know about life: it goes on.” -Robert Frost',
          '"The world will not treat you any better because you are a good person but that is no excuse not to be one."',
          '"A society grows great when old men plant trees whose shade they know they shall never sit in."',
          '“It’s better to be alone than in bad company” -George Washington',
          '"The best time to plant a tree was 20 years ago. The second best time is now."',
          '"Write it down. The mind may forget, but the paper will always remember."',
          '"A man who chases two chickens wears himself out and catches neither"',
          '"He who says he can and he who says he can\'t are both usually right."'
          '"Smooth seas don’t make for skillful sailors"',
          '"If you\'re gonna be dumb, you gotta be tough."',
          '"It\'s so easy to laugh\nIt\'s so easy to hate\nIt takes guts to be gentle and kind" - The Smiths, \'I Know It\'s Over\'',
          '"If your pictures aren\'t good enough, you aren\'t close enough." - Robert Capa',
          '"If I had a picture of two handcuffed criminals being booked, I\'d cut the picture in half and get five bucks for each." - Weegee',
          '"Don\'t panic."',
          '“The true price of anything you do is the amount of time you exchange for it.” ― Henry David Thoreau',
          '"“We are making photographs to understand what our lives mean to us.” — Ralph Hattersley',
          '"“The best thing about a picture is that it never changes, even when the people in it do.” — Andy Warhol',
          '“I never have taken a picture I’ve intended. They’re always better or worse.” — Diane Arbus',
          '"“If you want to be a better photographer, stand in front of more interesting stuff.” — Jim Richardson',
          '"Women may fake orgasms, but men can fake whole relationships." - Anna Nicole Smith',
          '"Tomorrow you can try again."',
          '"Get a big wall calendar that has a whole year on one page and hang it on a prominent wall. Then get a big red magic marker. For each day that you do your task, you get to put a big red X over that day. After a few days you\'ll have a chain. Just keep at it and the chain will grow longer every day. You\'ll like seeing that chain, especially when you get a few weeks under your belt. Your only job next is to not break the chain." - Jerry Seinfeld',
          '"I love a good nap. Sometimes it\'s the only thing getting me out of bed in the morning."- George Costanza',
          'Is it time for an oil change?',
          'When\'s the last time you changed your toothbrush?',
          'This app was created by john gallino in June 2019, and all these dumb quotes were chosen by him as well.',
          '"Almost everything will work again if you unplug it for a few minutes, including you."',
          '"For the longest time, I thought I needed to be more organized. Now I know I just needed less stuff."',
          '"I don’t say no because I’m so busy, I say no because I don’t want to be so busy."',
          '"I learned that thinking about living is not the same as living."',
          '"My goal is no longer to get more done, but rather to have less to do."',
          '"You can make more money, but you can’t make more time."',
          '"You will not understand the power and beauty of your youth until they have faded\nBut trust me, in 20 years you\'ll look back at photos of yourself\nand recall in a way you can\'t grasp now\nhow much possibility lay before you\nand how fabulous you really looked" - Everybody\'s Free To Wear Sunscreen',
          '"The best things in life aren’t things."',
          '"That was some weird shit." - George W. Bush, after Donald Trump\'s inauguration speech"',
          '"Desire wins."',
          '"Nobody in life gets exactly what they thought they were going to get. But if you work really hard and you\'re kind, amazing things will happen." - Conan O\'Brien',
          
          ]